import './globals.css'
import type { Metadata } from 'next'
import AuthProvider from './AuthProvider'
import { Navbar, ClientProvider } from '@/components'
import LoginModal from '@/components/modal/LoginModal'
import RegisterModal from '@/components/modal/RegisterModal'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`flex flex-col lg:flex-row`}>
        <AuthProvider>
          <ClientProvider>
            <LoginModal />
            <RegisterModal />
            <Navbar />
          </ClientProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
